// Fetches the daily JSON generated by the Python backend.
// In production this reads from the raw GitHub file.
// In dev, falls back to the local data/daily.json at the repo root.

export interface WeatherData {
  error: boolean
  message?: string
  city?: string
  temp_f?: number
  feels_like_f?: number
  high_f?: number
  low_f?: number
  description?: string
  icon?: string
  humidity?: number
  wind_mph?: number
  forecast?: { day: string; icon: string; high: number; low: number; description: string }[]
}

export interface StockItem {
  symbol: string
  name: string
  price: number
  change: number
  change_pct: number
  up: boolean
  is_crypto: boolean
  error?: boolean
}

export interface NewsArticle {
  title: string
  source: string
  url: string
  description: string
  published: string
  category: string
}

export interface Match {
  home: string
  away: string
  home_score: number | null
  away_score: number | null
  status: string
  time: string
  date: string
  highlighted: boolean
}

export interface Standing {
  position: number
  team: string
  played: number
  won: number
  drawn: number
  lost: number
  gd: number
  points: number
  highlighted: boolean
}

export interface CfaFrm {
  exam: string
  topic: string
  question: string
  options: Record<string, string>
  correct: string
  explanation: string
}

export interface FinanceTopic {
  title: string
  subtitle: string
  paragraphs: string[]
  key_takeaways: string[]
}

export interface JapaneseLesson {
  word: string
  reading: string
  meaning: string
  part_of_speech: string
  example_jp: string
  example_romaji: string
  example_en: string
  grammar_point: string
  grammar_explanation: string
  memory_tip: string
}

export interface AiStrategyContent {
  headline: string
  summary: string
  concepts: { term: string; definition: string }[]
  career_insight: string
}

export interface PLContent {
  transfer_news: { headline: string; summary: string; clubs: string[] }[]
  match_preview: { home: string; away: string; date: string; preview: string; key_players: string[] } | null
  injury_news: { player: string; team: string; status: string; return: string }[]
}

export interface DailyData {
  generated_at: string
  date: string
  weather: WeatherData
  stocks: { error: boolean; message?: string; tickers: StockItem[] }
  news: { error: boolean; message?: string; articles: NewsArticle[] }
  sports: { error: boolean; message?: string; matches: Match[]; standings: Standing[] }
  pl_content: PLContent
  ai: {
    error: boolean
    message?: string
    cfa_frm: CfaFrm
    finance_topic: FinanceTopic
    japanese: JapaneseLesson
    ai_strategy: AiStrategyContent
    market_sentiment: string
  }
}

const RAW_URL =
  'https://raw.githubusercontent.com/blainehalamuda-afk/daily-dashboard/main/data/daily.json'

export async function getDailyData(): Promise<DailyData | null> {
  try {
    const res = await fetch(RAW_URL, {
      next: { revalidate: 21600 }, // cache for 6 hours
    })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    return res.json()
  } catch (e) {
    console.error('Failed to fetch daily data:', e)
    return null
  }
}
